version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: my-redis-cache

  backend:
    image: trungaiot/backend-express-aiot:latest
    container_name: backend-express
    ports:
      - "3030:3030"
    environment:
      PORT: 3030
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DATABASE: ${SQL_DATABASE}
      REDIS_PORT: ${REDIS_PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
      HOST_IP: ${HOST_IP}
    depends_on:
      - mysql
      - redis

  frontend:
    image: trungaiot/frontend-nextjs-aiot:latest
    container_name: frontend-nextjs
    ports:
      - "3333:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

volumes:
  mysql_data:
