version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: aiot123 
      MYSQL_DATABASE: aiot            
      MYSQL_USER: admin                   
      MYSQL_PASSWORD: admin           
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: my-redis-cache

  backend:
    image: trungaiot/backend-express-aiot:latest
    container_name: backend-express
    ports:
      - "3030:3030"
    environment:
      PORT: 3030
      SQL_HOST: mysql
      SQL_PORT: 3306
      SQL_USER: admin
      SQL_PASSWORD: admin   
      SQL_DATABASE: aiot   
      REDIS_PORT: 6379
      FRONTEND_PORT: 3333
    depends_on:
      - mysql
      - redis

  frontend:
    image: trungaiot/frontend-nextjs-aiot:latest
    container_name: frontend-nextjs
    ports:
      - "3333:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
